[workspace]
resolver = "2"
members = [
    "crates/chain",
    "crates/macro",
    "crates/codegen",
    "crates/chaintester",
    "crates/struct-macro",
    # "tests",
    "examples"
]

exclude = [
    "tests"
]
