[package]
name = "structpacker"
description = "A proc-macro crate for StructPacker"
version = "0.1.0"
documentation = ""
edition = "2021"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"